In [45]:
# This file consists of embedding layer which shows you how to use embedding technique and convert the text to numberic value. 
from tensorflow.keras.preprocessing.text import one_hot

In [46]:
# Sentences 
text = [ 'the glass of milk',
         'the glass of juice',
         'the cup of tea',
         'i am a good boy',
         'i am a good developer',
         'understands the meaning of words',
         'your vedios are good']

In [47]:
# converting the words to vectors. 
voc_size = 10000

In [48]:
# one hot representation
one_hot_rep = [one_hot(words, voc_size) for words in text]
one_hot_rep
# These numbers explain the index of each words mentioned in the text. 

[[3105, 5899, 9575, 6087],
 [3105, 5899, 9575, 6569],
 [3105, 1106, 9575, 8720],
 [7611, 8540, 5985, 6681, 3302],
 [7611, 8540, 5985, 6681, 3903],
 [7818, 3105, 8715, 9575, 1577],
 [153, 9253, 21, 6681]]

In [49]:
# Word embeddings representation 

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [50]:
# there will be 8 words in the sentence 
sent_length = 8
Embedding_docs= pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(Embedding_docs)

[[   0    0    0    0 3105 5899 9575 6087]
 [   0    0    0    0 3105 5899 9575 6569]
 [   0    0    0    0 3105 1106 9575 8720]
 [   0    0    0 7611 8540 5985 6681 3302]
 [   0    0    0 7611 8540 5985 6681 3903]
 [   0    0    0 7818 3105 8715 9575 1577]
 [   0    0    0    0  153 9253   21 6681]]


In [51]:
# Feature representation 
dim = 10

In [52]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/pramitgarg/Desktop/Projects/Sentiment-Analysis-using-Simple-RNN/.venv/lib/python3.13/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [53]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [54]:
model.predict(Embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step


array([[[-0.02785163, -0.04978757, -0.02661707, -0.02756712,
          0.02540353,  0.01498764,  0.00361301,  0.02900579,
         -0.03138415, -0.00565917],
        [-0.02785163, -0.04978757, -0.02661707, -0.02756712,
          0.02540353,  0.01498764,  0.00361301,  0.02900579,
         -0.03138415, -0.00565917],
        [-0.02785163, -0.04978757, -0.02661707, -0.02756712,
          0.02540353,  0.01498764,  0.00361301,  0.02900579,
         -0.03138415, -0.00565917],
        [-0.02785163, -0.04978757, -0.02661707, -0.02756712,
          0.02540353,  0.01498764,  0.00361301,  0.02900579,
         -0.03138415, -0.00565917],
        [-0.01004291, -0.00866145, -0.04496764,  0.03810144,
         -0.0036252 ,  0.00966915,  0.01748297, -0.01125234,
          0.00080176, -0.03218376],
        [-0.0252191 , -0.01648115, -0.04380811, -0.00296137,
         -0.00240556,  0.03991512,  0.02264755,  0.04007052,
         -0.01823161, -0.00039748],
        [-0.03932476, -0.03080987,  0.04857303, -0.0

In [55]:
# Vectors of my first sentences of the text i mentioned above. 
Embedding_docs[0]

array([   0,    0,    0,    0, 3105, 5899, 9575, 6087], dtype=int32)

In [60]:
# Prediction 
model.predict(Embedding_docs[0])


ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>